# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Valerio Libera Software Engineer
email: info@valeriolibera.it
description: >- # this means to ignore newlines until "baseurl:"
  Computer Engineer, Software Developer, App & Full Stack Web Developer, Software Analyst, App Development

url: "https://www.valeriolibera.it" # the base hostname & protocol for your site, e.g. http://example.com
twitter_pagename: banorz1
facebook_pagename: ban23
linkedin_pagename: valerio-libera
github_pagename: banorz

collections:
  works:
    output: true
# Build settings
markdown: kramdown
# plugins:
#   - jekyll-feed
plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-minifier
  - jekyll-sitemap
jekyll-minifier:
  uglifier_args:
    harmony: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
languages: ["en","it"]
exclude_from_localizations: ["assets","css"]
